### ISSUE TITLE
支持ItemEff.img里头的特效(可用0xAA包头或ItemEffect激活) 请问一下括号里面具体是怎么实现？

### ISSUE THREAD

**Issue by long111d2** [Willh92/CMS079-ijl15#3]
screenshots/video about the resolution probloem here.
支持ItemEff.img里头的特效(可用0xAA包头或ItemEffect激活) 请问一下括号里面具体是怎么实现？

**Comment by Willh92** [comment]
发送包头0xAA 第一个int写入角色id 第二个int写入itemid

**Comment by long111d2** [comment]
> 发送包头0xAA 第一个int写入角色id 第二个int写入itemid，物品特效正确的话你就看到了

服务端源码吗？

**Comment by Willh92** [comment]
对

**Comment by long111d2** [comment]
请问有具体实现的写法吗？

**Comment by Willh92** [comment]
穿装备发包，脱了itemid发送0就是解除，具体的写法自己研究吧

**Comment by long111d2** [comment]
加上之后闪退
![30f70e39-9028-4ddc-aaad-646e8510d8fe](https://github.com/user-attachments/assets/f540414d-d0af-46a5-a477-0c6b08567657)

**Comment by Willh92** [comment]
你写入的是byte不是int

**Comment by long111d2** [comment]
谢谢  可以了

**Comment by long111d2** [comment]
期待你更多功能
